### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by rs22**
This adds a MIT license to the project. Please let me know if you have other suggestions for the project's license.

---
[Documentation of `add-license`](https://osmhpi.github.io/cohydra/add-license)

### CODE REVIEW

**Review by mgjm — CHANGES_REQUESTED** [review]
`ns-3` is licensed under _GNU GPLv2_ and `traci` is dual-licensed under _EPL-2.0_ and _GNU GPLv2+_.

All other dependencies are _MIT_, _Apache 2.0_ or  _GNU GPLv2+_ licensed.

Therefore the more permissive _MIT_ license is incompatible. But _GNU GPLv3+_ seems like a good option.

**Comment by rs22** [comment]
As usual when this question comes up, I need to do some research on what a 'derivative work' actually means. I found this posting compelling: https://opensource.stackexchange.com/a/1580

I think this project, as an 'orchestration tool' to wire up user applications with a network simulator (and optionally other simulators), does not strictly require traci and sumo to be a functioning 'whole work'. Hence, we should be able to choose our license regardless of how traci is licensed.

With ns-3, as it currently stands, it's probably a different story. Although I can imagine that other types of 'software-defined networking libraries' can be used as the backend for certain use cases, we currently heavily depend on ns-3. So in effect, I agree with you.

What is your opinion with regards to your own contributions? Regardless of the dependencies -- do you prefer a 'free software' license or would you agree to a 'permissive' license, if that was an option?

**Comment by felix-gohla** [comment]
Thanks for the SE post.

I also agree that we use `ns-3` as the testbed's main component. Therefore *MIT* would not fit.
At least when considering the dependencies. Otherwise I'd be totally fine with a MIT license.

Do I remember correctly that *GPLv2* and *GPLv3* are incompatible?
Using the GPLv2(+)-dependencies (ns-3 as shared libraries) would mean we are committed to using this license, too, aren't we?

**Comment by arneboockmeyer** [comment]
Replaced by https://github.com/diselab/marvis/issues/2

**Pull request closed without merging**
