### PR TITLE
Updates Dockerfiles for Docker Hub auto-builds

### PR DESCRIPTION
**Pull request by rs22**
We now have a Docker Hub configuration in place that builds the osmhpi/cohydra and osmhpi/cohydra:base images automatically: https://hub.docker.com/r/osmhpi/cohydra

Since Docker Hub unnecessarily clones the master branch (and its submodules) first, before switching to this feature branch, I needed to take a shortcut and removed the private submodules for the sumo example on the master branch already. Going forward, if @arneboockmeyer decides to publish this code, we might rather have a separate repository with sumo experiments (the use of sumo is well documented in the docs, I think).

Is the cohydra-dev image actually still required? Or is the .devcontainer/Dockerfile sufficient for development?

---
[Documentation of `feature/updated-dockerfiles`](https://osmhpi.github.io/cohydra/feature/updated-dockerfiles)

### CODE REVIEW

**Comment by mgjm** [comment]
As `ns-3` and `traci` can now be installed via https://github.com/osmhpi/python-wheels/releases/latest we can add a `requirements.txt` and `setup.py` and finally fix #11.

My suggestion would be to completely switch to using pip as the primary install method.
Therefore wo would no longer need the `osmhpi/ns-3` docker image and we could provide just one `osmhpi/cohydra` Docker image which would `pip install git+https://github.com/osmhpi/cohydra.git` and install useful tools required when running simulations with cohydra (e.g. `docker-cli`).

Should this change be part of this PR?

**Comment by rs22** [comment]
Could you set up a separate PR for adding the requirements.txt and setup.py? I agree that we should switch to pip as the primary install method.

However, I'd like to keep the ns-3 Dockerfile (and also automated Docker builds) -- it can be useful in other contexts as well and therefore now lives in a separate repository.

By convention, I think the osmhpi/cohydra image should be somewhat minimal and 'vanilla', as it currently is.

**Review by mgjm — APPROVED** [review]

**Review by felix-gohla — APPROVED** [review]
LGTM :)

**Comment by felix-gohla** [comment]
> Is the cohydra-dev image actually still required? Or is the .devcontainer/Dockerfile sufficient for development?

I don't see an advantage in keeping the `dev` image. If @mgjm doesn't mind, we could delete it.

**Comment by rs22** [comment]
Thanks! Regarding the cohydra:dev image, I changed my mind: I might have a use case for it soon, maybe I'll extend it then.

**Comment by mgjm** [comment]
@felix-gohla @rs22 The `:dev` image can be used to develop scenarios using cohydra as a dependency and the `.devcontainer/Dockerfile` can be used to develop cohydra it self (It therefore does not contain the cohydra package).

**Pull request merged**
