### PR TITLE
WIP: Support sumo step length

### LINKED ISSUE #12: Support SUMO step length

### PR DESCRIPTION
**Pull request by arneboockmeyer**
fix #12

### CODE REVIEW

**Comment by arneboockmeyer** [comment]
@rs22 This could not be tested so for because of #10

**Comment by felix-gohla** [comment]
We're currently working on getting the docker images up on DockerHub, therefore this is not well documented. Furthermore, there is one more merge request in the Gitlab (see https://gitlab.hpi.de/robert.schmid/testbed-temp/merge_requests/2).

A quick workaround for testing would be running the testbed outside of the Docker container or pass the following arguments while starting the container: `-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix`. You then should be able to use the GUI-version of SUMO.

**Comment by arneboockmeyer** [comment]
Okay, I will try that. Could you please move that PR from GitLab to GitHub? We should prevent working in two repositories at the same time.

**Comment by felix-gohla** [comment]
Yes, I'll do so. But beforehand I want to clean up the merge request like you requested and then I will push it to GitHub.

**Comment by arneboockmeyer** [comment]
Replaced by #19

**Pull request closed without merging**
